### ISSUE TITLE
Todo for this week

### ISSUE THREAD

**Issue by hiromipaw** [fablabbcn/fablabs#50]
To do/to fix:
- [x] Fix user mailers
    - [x] User is not mailed
    - [x] Referee is mailed as if they were the users
    - [x] Need more info doesn't send emails
    - [x] On more infor added doesn't send emails
- [x] Add referee mailers
- [x] Check admin mailers
- [ ] Improve test coverage
- [ ] Reduce overall complexity  
- [ ] Address opbeat errors
- [ ] Add voting machine
- [ ] Add compulsory checkboxes
    - [ ] The submitted Fab Lab is committed with the principles of the Fab Lab Charter: http://www.fabfoundation.org/fab-labs/the-fab-charter/
    - [ ] The submitted Fab Lab has a compatible set of tools related with the official fab lab inventory
    - [ ] The submitted Fab Lab commits to participate in the network activities: regional meetings, FABX conferences
    - [ ] Our staff is (or will be) trained in the Fab Academy or compatible programs
